CREATE SCHEMA ISSUE_TRACKER;

CREATE TABLE ISSUE_TRACKER.USER
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username varchar(50) not null
);

CREATE TABLE ISSUE_TRACKER.ISSUE
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title       varchar(255) not null,
    description varchar(255) not null,
    status      varchar(20)  not null,
    reporter    BIGINT       not null,
    assignee    BIGINT,
    message     BIGINT,
    created     DATE         NOT NULL,
    completed   DATE
);

CREATE TABLE ISSUE_TRACKER.MESSAGE
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message     varchar(255) not null,
    user        BIGINT       not null
);

ALTER TABLE ISSUE_TRACKER.ISSUE
    ADD FOREIGN KEY (reporter)
        REFERENCES ISSUE_TRACKER.USER (id);

ALTER TABLE ISSUE_TRACKER.ISSUE
    ADD FOREIGN KEY (assignee)
        REFERENCES ISSUE_TRACKER.USER (id);

ALTER TABLE ISSUE_TRACKER.ISSUE
    ADD FOREIGN KEY (message)
        REFERENCES ISSUE_TRACKER.MESSAGE (id);

ALTER TABLE ISSUE_TRACKER.MESSAGE
    ADD FOREIGN KEY (user)
        REFERENCES ISSUE_TRACKER.USER (id);


INSERT INTO ISSUE_TRACKER.USER (username)
VALUES ('j.jones');
INSERT INTO ISSUE_TRACKER.USER (username)
VALUES ('h.humble');

INSERT INTO ISSUE_TRACKER.MESSAGE (message, user)
VALUES ('This is a comment related to Issue 1',
        (select id from ISSUE_TRACKER.USER where USER.username = 'j.jones'));

INSERT INTO ISSUE_TRACKER.ISSUE (title, description, status, reporter, created, message)
VALUES ('Issue.java number one',
        'This is issue number one',
        'backlog',
        (select id from ISSUE_TRACKER.USER where USER.username = 'j.jones'),
        '2017-08-01',
        (select id from ISSUE_TRACKER.MESSAGE where MESSAGE.message = 'This is a comment related to Issue 1'));

INSERT INTO ISSUE_TRACKER.ISSUE (title, description, status, reporter, created)
VALUES ('Issue.java number two',
        'This is issue number two',
        'backlog',
        (select id from ISSUE_TRACKER.USER where USER.username = 'h.humble'),
        '2017-08-01');

INSERT INTO ISSUE_TRACKER.ISSUE (title, description, status, reporter, assignee, created, completed)
VALUES ('Issue.java number three',
        'This is issue number three',
        'done',
        (select id from ISSUE_TRACKER.USER where USER.username = 'h.humble'),
        (select id from ISSUE_TRACKER.USER where USER.username = 'h.humble'),
        '2017-07-22',
        '2017-08-02');

INSERT INTO ISSUE_TRACKER.ISSUE (title, description, status, reporter, assignee, created, completed)
VALUES ('Issue.java number four',
        'This is issue number four',
        'done',
        (select id from ISSUE_TRACKER.USER where USER.username = 'h.humble'),
        (select id from ISSUE_TRACKER.USER where USER.username = 'j.jones'),
        '2017-08-02',
        '2017-08-02');

INSERT INTO ISSUE_TRACKER.ISSUE (title, description, status, reporter, assignee, created)
VALUES ('Issue.java number five',
        'This is issue number five',
        'in_progress',
        (select id from ISSUE_TRACKER.USER where USER.username = 'j.jones'),
        (select id from ISSUE_TRACKER.USER where USER.username = 'j.jones'),
        '2017-08-02');